from typing import Any, Callable, Protocol, Sequence, SupportsIndex

class SupportsStr(Protocol):
    def __str__(self) -> str: ...

type ParseStrat = Callable[[str], Any]

PARSE_STRATS: dict[str, ParseStrat] = {}

def parser(ext: str) -> Callable[[ParseStrat], ParseStrat]: ...
def get_extension(path: SupportsStr) -> str: ...
def parse(text: str, method: str) -> Any: ...
def split_obj_path(path: str, delim: str = "/") -> tuple[str | int, ...]: ...
def deep_get(target: Any, path: Sequence[str | SupportsIndex]) -> Any: ...
def split_sequence[T](
    seq: Sequence[T], delim: T, *, maxsplit: int | None = None
) -> tuple[Sequence[T], ...]: ...
def resolve_path(
    target: Any, path: Sequence[str | SupportsIndex], delim: str = "*"
) -> Any: ...
def match_wildcard(pattern: str, string: str, delim: str = "*") -> bool: ...
